/* AUTH */
export const REGISTRATION = 'REGISTRATION';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CHECK_AUTH = 'CHECK_AUTH';
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';
export const CHECK_AUTH_ERROR = 'CHECK_AUTH_ERROR';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

/* APP */
export const FETCH_INITIAL_DATA = 'FETCH_INITIAL_DATA';
export const FETCH_INITIAL_DATA_SUCCESS = 'FETCH_INITIAL_DATA_SUCCESS';
export const FETCH_INITIAL_DATA_ERROR = 'FETCH_INITIAL_DATA_ERROR';

export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* BOOKS */
export const FETCH_BOOKS = 'FETCH_BOOKS';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR';

export const FETCH_BOOK = 'FETCH_BOOK';
export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS';
export const FETCH_BOOK_ERROR = 'FETCH_BOOKS_ERROR';

export const CREATE_BOOK = 'CREATE_BOOK';
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
export const CREATE_BOOK_ERROR = 'CREATE_BOOK_ERROR';

export const REMOVE_BOOK = 'REMOVE_BOOK';
export const REMOVE_BOOK_SUCCESS = 'REMOVE_BOOK_SUCCESS';
export const REMOVE_BOOK_ERROR = 'REMOVE_BOOK_ERROR';

export const UPDATE_BOOK = 'UPDATE_BOOK';
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
export const UPDATE_BOOK_ERROR = 'UPDATE_BOOK_ERROR';

/* USERS */
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

/* TRACKINGS */

export const CREATE_TRACKING = 'CREATE_TRACKING';
export const CREATE_TRACKING_SUCCESS = 'CREATE_TRACKING_SUCCESS';
export const CREATE_TRACKING_ERROR = 'CREATE_TRACKING_ERROR';

export const FETCH_TRACKINGS = 'FETCH_TRACKINGS';
export const FETCH_TRACKINGS_SUCCESS = 'FETCH_TRACKINGS_SUCCESS';
export const FETCH_TRACKINGS_ERROR = 'FETCH_TRACKINGS_ERROR';

export const FETCH_TRACKING = 'FETCH_TRACKING';
export const FETCH_TRACKING_SUCCESS = 'FETCH_TRACKING_SUCCESS';
export const FETCH_TRACKING_ERROR = 'FETCH_TRACKING_ERROR';

export const REMOVE_TRACKING = 'REMOVE_TRACKING';
export const REMOVE_TRACKING_SUCCESS = 'REMOVE_TRACKING_SUCCESS';
export const REMOVE_TRACKING_ERROR = 'REMOVE_TRACKING_ERROR';

/* REVIEWS */
export const FETCH_REVIEWS= 'FETCH_REVIEWS';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_ERROR = 'FETCH_REVIEWS_ERROR';

export const FETCH_REVIEW = 'FETCH_REVIEW';
export const FETCH_REVIEW_SUCCESS = 'FETCH_REVIEW_SUCCESS';
export const FETCH_REVIEW_ERROR = 'FETCH_REVIEW_ERROR';

export const CREATE_REVIEW = 'CREATE_REVIEW';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_ERROR = 'CREATE_REVIEW_ERROR';

export const REMOVE_REVIEW = 'REMOVE_REVIEW';
export const REMOVE_REVIEW_SUCCESS = 'REMOVE_REVIEW_SUCCESS';
export const REMOVE_REVIEW_ERROR = 'REMOVE_REVIEW_ERROR';

export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_ERROR = 'UPDATE_REVIEW_ERROR';

export const TOGGLE_LEFT_PANEL = 'TOGGLE_LEFT_PANEL';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const BOOKS_FILTER_TITLE = 'BOOKS_FILTER_TITLE';

export const BOOKS_FILTER_GENRE = 'BOOKS_FILTER_GENRE';

export const BOOKS_FILTER_AUTHOR = 'BOOKS_FILTER_AUTHOR';

export const BOOKS_CLEAR_FILTERS = 'BOOKS_CLEAR_FILTERS';